"""Add post_id to images table

Revision ID: 228034533a2c
Revises: f4fe28ceada3
Create Date: 2026-03-12 04:43:33.369820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228034533a2c'
down_revision = 'f4fe28ceada3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_images_post_id', 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint('fk_images_post_id', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
